/* SW Version: 1.0.5 - Ultimate Resilience */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', (event) => {
    console.log('[SW] Service Worker Installing...');
    event.waitUntil(self.skipWaiting()); // Força a nova versão a assumir agora
});

self.addEventListener('activate', (event) => {
    console.log('[SW] Service Worker Activated! Ready for push.');
    event.waitUntil(self.clients.claim()); // Começa a controlar as abas agora mesmo
});

self.addEventListener('push', (event) => {
    console.log('[SW] Push event incoming...');

    let title = 'Novo aviso - TutShop';
    let options = {
        body: 'Você recebeu uma atualização no sistema.',
        icon: '/app-icon-v3.png',
        badge: '/app-icon-v3.png',
        tag: 'tutshop-alert',
        renotify: true,
        requireInteraction: true, // Garante que não suma no PC sem ver
        data: { url: '/dashboard' }
    };

    if (event.data) {
        try {
            const data = event.data.json();
            title = data.title || title;
            options.body = data.body || options.body;
            if (data.data?.url) options.data.url = data.data.url;
        } catch (e) {
            options.body = event.data.text();
        }
    }

    event.waitUntil(
        self.registration.showNotification(title, options)
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const urlToOpen = event.notification.data.url;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open at the URL, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
