/* SW Version: 1.0.5 - Ultimate Resilience */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', () => {
    console.log('[SW] Service Worker Installing...');
});

self.addEventListener('activate', () => {
    console.log('[SW] Service Worker Activated! Ready to receive push notifications.');
});

self.addEventListener('push', (event) => {
    console.log('[SW] Push event received!');

    let title = 'TutShop Marketplace';
    let options = {
        body: 'Você tem uma nova mensagem ou atualização.',
        icon: '/app-icon-v3.png',
        badge: '/app-icon-v3.png',
        vibrate: [100, 50, 100],
        data: { url: '/dashboard' }
    };

    if (event.data) {
        try {
            const data = event.data.json();
            console.log('[SW] Push data (JSON):', data);

            title = data.title || title;
            options.body = data.body || options.body;
            options.icon = data.icon || options.icon;
            if (data.data) {
                options.data = { ...options.data, ...data.data };
            }
        } catch (e) {
            console.error('[SW] Could not parse push data as JSON, using as text:', e);
            options.body = event.data.text();
        }
    } else {
        console.warn('[SW] Push event received but no data found.');
    }

    event.waitUntil(
        self.registration.showNotification(title, options)
            .then(() => console.log('[SW] Notification shown successfully!'))
            .catch(err => console.error('[SW] Failed to show notification:', err))
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const urlToOpen = event.notification.data.url;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open at the URL, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
