/* SW Version: 1.2.2 - Ultimate Resilience */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', (event) => {
    console.log('[SW] Service Worker Installing...');
    event.waitUntil(self.skipWaiting()); // Força a nova versão a assumir agora
});

self.addEventListener('activate', (event) => {
    console.log('[SW] Service Worker Activated! Ready for push.');
    event.waitUntil(self.clients.claim()); // Começa a controlar as abas agora mesmo
});

// Erros globais do SW para o Dashboard
self.addEventListener('error', (event) => {
    logToUI('CRITICAL SW ERROR! ❌', event.message);
});

self.addEventListener('unhandledrejection', (event) => {
    logToUI('SW PROMISE REJECTED! ❌', event.reason);
});

// Comandos diretos do Dashboard para o SW
self.addEventListener('message', (event) => {
    if (event.data === 'PING') {
        logToUI('PONG! Service Worker está VIVO e respondendo. ⚡');
    }

    if (event.data === 'SIMULATE_PUSH') {
        logToUI('Iniciando simulação interna... 🕹️');
        const simulatedEvent = new Event('push');
        // @ts-ignore
        simulatedEvent.simulated = true;
        // Adicionando dados simulados
        Object.defineProperty(simulatedEvent, 'data', {
            value: {
                json: () => ({ title: '📣 Teste Simulado (v1.2.1)', body: 'Se você vê isso, o SW consegue abrir balões!' }),
                text: () => 'Teste Simulado'
            }
        });
        self.dispatchEvent(simulatedEvent);
    }
});

const logChannel = new BroadcastChannel('sw-logs');
function logToUI(msg, data = null) {
    const timestamp = new Date().toLocaleTimeString();
    logChannel.postMessage({ timestamp, msg, data });
    console.log(`[SW ${timestamp}] ${msg}`, data || '');
}

self.addEventListener('push', (event) => {
    // @ts-ignore
    const isSimulated = event.simulated === true;
    logToUI(isSimulated ? 'Simulando recebimento de sinal... 🧪' : 'SINAL REAL RECEBIDO DA NUVEM! 🚀📡');

    let title = '🔔 Atualização TutShop';
    let options = {
        body: 'Você recebeu uma nova atualização no marketplace.',
        icon: '/app-icon-v3.png',
        badge: '/app-icon-v3.png',
        tag: 'tutshop-remote-alert',
        renotify: true,
        requireInteraction: true,
        data: { url: '/dashboard' }
    };

    if (event.data) {
        try {
            const data = event.data.json();
            logToUI('Dados JSON processados:', data);
            title = data.title || title;
            options.body = data.body || options.body;
            if (data.data?.url) options.data.url = data.data.url;
        } catch (e) {
            logToUI('Erro ao processar JSON, tentando Texto...');
            const text = event.data.text();
            logToUI('Dados TEXTO processados:', text);
            options.body = text;
        }
    } else if (!isSimulated) {
        logToUI('ALERTA: Evento PUSH REAL sem dados.');
    }

    const showPromise = self.registration.showNotification(title, options)
        .then(() => logToUI('Notificação exibida com sucesso! ✅'))
        .catch(err => logToUI('ERRO ao exibir notificação: ❌', err.message));

    if (event.waitUntil) {
        event.waitUntil(showPromise);
    }
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const urlToOpen = event.notification.data.url;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open at the URL, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
